version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"  # You can change this to any available port
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ems
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Onthemoon29!
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: Onthemoon29!
    ports:
      - "3306:3306"  # Default MySQL port
